# Generated by Django 5.0.1 on 2026-01-31 06:21

from django.db import migrations
from datetime import date

def crear_datos_ejemplo(apps, schema_editor):
    """Crea datos de ejemplo para los modelos."""
    Categoria = apps.get_model('productos', 'Categoria')
    Producto = apps.get_model('productos', 'Producto')
    Embarque = apps.get_model('productos', 'Embarque')

    # Crear Categorías
    cat_electronica = Categoria.objects.create(nombre='Electrónica', descripcion='Dispositivos y gadgets electrónicos.')
    cat_ropa = Categoria.objects.create(nombre='Ropa', descripcion='Prendas de vestir y accesorios.')
    cat_hogar = Categoria.objects.create(nombre='Hogar', descripcion='Artículos para el hogar y decoración.')

    # Crear Productos
    prod_laptop = Producto.objects.create(
        nombre='Laptop Pro X',
        precio=1200.50,
        stock=15,
        categoria=cat_electronica
    )
    prod_smartphone = Producto.objects.create(
        nombre='Smartphone Z1',
        precio=850.00,
        stock=30,
        categoria=cat_electronica
    )
    prod_camiseta = Producto.objects.create(
        nombre='Camiseta de Algodón',
        precio=25.99,
        stock=100,
        categoria=cat_ropa
    )
    prod_silla = Producto.objects.create(
        nombre='Silla de Oficina Ergonómica',
        precio=150.75,
        stock=20,
        categoria=cat_hogar
    )

    # Crear Embarques y asociar productos
    embarque1 = Embarque.objects.create(codigo_rastreo='TRACK-US-2026-001', fecha_llegada=date(2026, 2, 15))
    embarque1.productos.set([prod_laptop, prod_smartphone])

    embarque2 = Embarque.objects.create(codigo_rastreo='TRACK-CN-2026-002', fecha_llegada=date(2026, 2, 20))
    embarque2.productos.set([prod_camiseta, prod_silla])

    embarque3 = Embarque.objects.create(codigo_rastreo='TRACK-EU-2026-003', fecha_llegada=date(2026, 3, 1))
    embarque3.productos.set([prod_laptop, prod_silla])


def borrar_datos_ejemplo(apps, schema_editor):
    """Elimina los datos de ejemplo creados."""
    Categoria = apps.get_model('productos', 'Categoria')
    Producto = apps.get_model('productos', 'Producto')
    Embarque = apps.get_model('productos', 'Embarque')

    Embarque.objects.filter(codigo_rastreo__startswith='TRACK-').delete()
    Producto.objects.filter(nombre__in=['Laptop Pro X', 'Smartphone Z1', 'Camiseta de Algodón', 'Silla de Oficina Ergonómica']).delete()
    Categoria.objects.filter(nombre__in=['Electrónica', 'Ropa', 'Hogar']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(crear_datos_ejemplo, reverse_code=borrar_datos_ejemplo),
    ]