# Generated by Django 5.0.1 on 2026-01-31 06:26

from django.db import migrations
from django.conf import settings
import os
from PIL import Image, ImageDraw, ImageFont

def crear_imagenes_ejemplo(apps, schema_editor):
    """Genera imágenes de placeholder para los productos de ejemplo."""
    Producto = apps.get_model('productos', 'Producto')
    
    # Asegurarse de que el directorio de media/productos existe
    media_dir = os.path.join(settings.MEDIA_ROOT, 'productos')
    os.makedirs(media_dir, exist_ok=True)

    # Fuente (puede necesitar ajuste de ruta en otros sistemas)
    try:
        font = ImageFont.truetype("arial.ttf", 24)
    except IOError:
        font = ImageFont.load_default()

    productos_data = {
        'Laptop Pro X': {'color': '#4a4a4a', 'file': 'laptop.png'},
        'Smartphone Z1': {'color': '#5a5a5a', 'file': 'smartphone.png'},
        'Camiseta de Algodón': {'color': '#6a6a6a', 'file': 'camiseta.png'},
        'Silla de Oficina Ergonómica': {'color': '#7a7a7a', 'file': 'silla.png'},
    }

    for nombre_producto, data in productos_data.items():
        try:
            producto = Producto.objects.get(nombre=nombre_producto)
            img_path = os.path.join(media_dir, data['file'])
            
            # Crear imagen
            img = Image.new('RGB', (600, 400), color=data['color'])
            d = ImageDraw.Draw(img)
            
            # Dibujar texto
            text = f"{producto.nombre}\n(Placeholder)"
            d.text((300, 200), text, fill=(255, 255, 255), font=font, anchor="mm")
            
            # Guardar imagen
            img.save(img_path)
            
            # Actualizar modelo
            producto.imagen = os.path.join('productos', data['file'])
            producto.save()

        except Producto.DoesNotExist:
            # Si el producto no existe, simplemente continuamos
            continue

def borrar_imagenes_ejemplo(apps, schema_editor):
    """Elimina las imágenes de placeholder generadas."""
    Producto = apps.get_model('productos', 'Producto')
    productos_data = {
        'Laptop Pro X': {'file': 'laptop.png'},
        'Smartphone Z1': {'file': 'smartphone.png'},
        'Camiseta de Algodón': {'file': 'camiseta.png'},
        'Silla de Oficina Ergonómica': {'file': 'silla.png'},
    }

    for nombre_producto, data in productos_data.items():
        try:
            producto = Producto.objects.get(nombre=nombre_producto)
            if producto.imagen:
                # Borrar archivo físico
                img_path = os.path.join(settings.MEDIA_ROOT, producto.imagen.name)
                if os.path.exists(img_path):
                    os.remove(img_path)
                
                # Limpiar campo en la BD
                producto.imagen = None
                producto.save()
        except Producto.DoesNotExist:
            continue

class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20260131_0121'),
    ]

    operations = [
        migrations.RunPython(crear_imagenes_ejemplo, reverse_code=borrar_imagenes_ejemplo),
    ]